name: Generate javadoc github pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate documentation directory
        uses: gradle/gradle-build-action@v2
        with:
          arguments: javadocJar
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './build/docs/javadoc'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
